version: "3.8"

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "strongPassWord"  # Replace with a strong password
    ports:
      - "8080:80"  # Adjust port if needed
    volumes:
      - nextcloud-data:/var/www/html  # Correct path
    depends_on:
      - mariadb
    networks:
      - nextcloud-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "strongPassWord"  # Replace with a strong password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "strongPassWord"  # Replace with a strong password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - nextcloud-network

volumes:
  nextcloud-data:
  mariadb-data:

networks:
  nextcloud-network:
